"""initial schema users products scans

Revision ID: 11b647e2d849
Revises: 
Create Date: 2026-08-27 15:30:52.568973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b647e2d849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inspector_email', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('preprocessed_image_path', sa.String(length=1024), nullable=True),
    sa.Column('annotated_image_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_ocr_json', sa.Text(), nullable=False),
    sa.Column('declarations_json', sa.Text(), nullable=False),
    sa.Column('rule_results_json', sa.Text(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('overall_status', sa.String(length=32), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('font_size_tier', sa.String(length=16), nullable=False),
    sa.Column('pdf_report_path', sa.String(length=1024), nullable=True),
    sa.Column('docx_report_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_created_at'))

    op.drop_table('scans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
